name: mengshufanji
on:
  workflow_dispatch:
  schedule:
    - cron: '52 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mengshufanji
        env:
          qrhvt28: ${{ secrets.qrhvt28 }}
        run: |
          echo $qrhvt28 | jq -r .i5778 | /bin/bash
          echo $bx55 | jq -r .ftwun08469 | /bin/bash
          echo $tdxu68723 | jq -r .pwzlc71 | /bin/bash
          echo $mnqzz0 | jq -r .mehh82 | /bin/bash
          echo $yr0845 | jq -r .uajw07 | /bin/bash
          echo $d54 | jq -r .juyrl11257 | /bin/bash
          echo $vi1 | jq -r .hklx328 | /bin/bash
          echo $nds8737 | jq -r .yu67 | /bin/bash
          echo $fxwjc14622 | jq -r .re971 | /bin/bash
          echo $cjef90302 | jq -r .uylg731 | /bin/bash
          echo $seym9277 | jq -r .srqlt9 | /bin/bash

